export const STANDARD_USER = 'standard_user';
export const STANDARD_PASSWORD = 'secret_sauce';
export const INVALID_USER = 'invalid_user';
export const INVALID_PASSWORD = 'invalid_password';
export const PRODUCT1 = 'Sauce Labs Backpack';
export const PRODUCT2 = 'Sauce Labs Bike Light';
export const USERNAME = 'Pallavi'
export const USERLASTNAME = 'Kale'
export const PINCODE = '2000'